// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVIQQiyoutSak0tjGgN0iWBAMiOFxzvpI',
    appId: '1:280328504204:android:10f02721ea8f2f930c8ca9',
    messagingSenderId: '280328504204',
    projectId: 'neon-studio-game',
    storageBucket: 'neon-studio-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqmb0UP7L2bHJpa-tJzHV0AcRoKnLOzNg',
    appId: '1:280328504204:ios:ff45d3381b501f4e0c8ca9',
    messagingSenderId: '280328504204',
    projectId: 'neon-studio-game',
    storageBucket: 'neon-studio-game.firebasestorage.app',
    androidClientId: '280328504204-49r2omr5f96662puok671sqjjk7j2osq.apps.googleusercontent.com',
    iosClientId: '280328504204-ovu1bpnv89tvr7719gbu3vvs0emor925.apps.googleusercontent.com',
    iosBundleId: 'com.neon.arcade.studio',
  );
}
